<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-12 at 12:33:59.
 */
class AppRegistryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AppRegistry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AppRegistry;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
