<?php
require_once '../AppRegistry.php';
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-12 at 13:33:35.
 */
const HOME_PATH = "/home/serj0987/";

class AppRegistryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AppRegistry
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }
    
    function testInitHome()
    {
        $this->object = new AppRegistry('~/');
        $this->assertEquals(rtrim("/home/serj0987","/\\"), $this->object->getScanDir());
    }
    
    function testInitThis()
    {
        $this->object = new AppRegistry("./");
        $this->assertEquals(rtrim("./","/\\"), $this->object->getScanDir());
    }
    

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
