<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-15 at 12:18:52.
 */
require_once '../ErrorBox.php';
require_once '../Exceptions.php';
class ErrorBoxTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ErrorBox
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = ErrorBox::getInstance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ErrorBox::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        $this->assertEquals(get_class(ErrorBox::getInstance()), "ErrorBox");
    }

    /**
     * @covers ErrorBox::getException
     * @todo   Implement testGetException().
     */
    public function testGetExceptionCode0() {
        try {
            $this->object->getException(0);
            
        } catch (Exception $exc) {
            $this->assertEquals($exc->getMessage(),'Unknown error');
            return;
        }
        $this->fail('Method not generate exceptions'); 
    }
    
        public function testGetExceptionCode3() {
        try {
            $this->object->getException(3);
            
        } catch (AppRegistryException $exc) {
            $this->assertEquals($exc->getMessage(),'Wrong scan dir path');
            return;
        } catch (Exception $exc) {
            $this->fail('Wrong exception type'); 
        }
        
        $this->fail('Method not generate exceptions'); 
    }
    

}
