<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-20 at 08:45:20.
 */
require_once '../FileFinder.php';
require_once '../Exceptions.php';
require_once '../archiver/ZipArchiver.php';
require_once '../archiver/GzArchiver.php';
require_once '../archiver/BzArchiver.php';

class FileFinderTest extends PHPUnit_Framework_TestCase {

    /**
     * @var FileFinder
     */
    protected $object;
    private $output_zip_file = '/home/serj0987/1.zip';
    private $output_gz_file = '/home/serj0987/1.tar.gz';
    private $output_bz_file = '/home/serj0987/12.tar.bz2';
    private $class;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        @mkdir('t');
        $arc = new ZipArchiver();
        
        $arc->open($this->output_zip_file);
   
        $this->class = new ReflectionClass('FileFinder');
        
        $this->object = new FileFinder($arc, '/home/serj0987');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        @unlink($this->output_zip_file);
        @unlink($this->output_gz_file);
        @unlink('t');
        //@unlink($this->output_gz_file.'.gz');
        
    }

    /**
     * @covers FileFinder::createBackup
     * @todo   Implement testCreateBackup().
     */
    public function testCreateZipBackup() {
        $arc = $this->object->createBackup();
        $result = $arc->close();

        if (!file_exists($this->output_zip_file))
            $this->fail('Backup zip file is not exist');
    }
    
    public function testCreateGzBackup() {
        $arc = new GzArchiver();
        
        $arc->open($this->output_gz_file);
   
        $this->class = new ReflectionClass('FileFinder');
        
        $object = new FileFinder($arc, '/home/serj0987');
        $arc = $object->createBackup();
        $result = $arc->close();

        if (!file_exists($this->output_gz_file))
            $this->fail('Backup tar.gz file is not exist');
    }
    
    public function testCreateBzBackup() {
        $arc = new BzArchiver();
        
        $arc->open($this->output_bz_file);
   
        $this->class = new ReflectionClass('FileFinder');
        
        $object = new FileFinder($arc, '/home/serj0987');
        $arc = $object->createBackup();
        $result = $arc->close();

        if (!file_exists($this->output_bz_file))
            $this->fail('Backup tar.bz file is not exist');
    }
    
    
    public function testGetLocalArcFilename1() {

        $method = $this->class->getMethod('getLocalArcFilename');
        $method->setAccessible(true);
        
        $result = $method->invoke($this->object, 
                '.bitcoin');
        $this->assertEquals($result, 'bitcoin/wallet.dat');
        
    }
    
        public function testGetLocalArcFilename2() {

        $method = $this->class->getMethod('getLocalArcFilename');
        $method->setAccessible(true);
        
        $result = $method->invoke($this->object, 
                'bitcoin');
        $this->assertEquals($result, FALSE);
        
    }
    
        public function testGetRealFilename1() {

        $method = $this->class->getMethod('getRealFilename');
        $method->setAccessible(true);
        
        $result = $method->invoke($this->object, 
                '/home/serj0987', '.bitcoin');
        
        $this->assertEquals($result, '/home/serj0987/.bitcoin/wallet.dat');
        
    }
    
        public function testGetRealFilename2() {

        $method = $this->class->getMethod('getRealFilename');
        $method->setAccessible(true);
        
        $result = $method->invoke($this->object, 
                '/home/serj098778', '.bitcoin');
        
        $this->assertEquals($result, FALSE);
        
    }
    


}
